version: "3.8"
services:
  backend:
    build:
      context: ./calculadora-emprestimos-backend
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./calculadora-emprestimos-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
